feat(pyproject): add sane default settings
Lolomgrofl/fastapi_genesis pull request #23
Opened 2023-07-16 09:12 UTC by grski

for ruff, ruff isort  and remove setup.cfg as it's only used for flake8 which we can remove if we use ruff

2023-07-18 01:44 UTC, CarlosLugones commented
Nice! I had no idea this was possible with Poetry.

2023-07-18 03:36 UTC, grski commented
@CarlosLugones it comes bundles with ruff, pyproject is just a standard way of config that Poetry promoted 👍  and thank you!

2023-07-19 20:41 UTC, adamjanas commented on {{cookiecutter.repo_name}}/pyproject.toml
> +section-order = ["fastapi", "future", "standard-library", "third-party",  "first-party", "local-folder"]
@grski place future imports right before `fastapi` (as first)

2023-07-20 14:30 UTC, Lolomgrofl requested changes

2023-07-20 14:30 UTC, Lolomgrofl commented on {{cookiecutter.repo_name}}/pyproject.toml
> +)/
exclude `alembic` here as well

2023-07-20 17:41 UTC, grski commented
@Lolomgrofl @adamjanas resolved.

2023-07-20 18:00 UTC, Lolomgrofl commented
@grski pre-commit failed

2023-07-20 18:24 UTC, grski commented
Finally.
Should be good.

2023-07-20 18:30 UTC, Lolomgrofl approved these changes

2023-07-20 18:30 UTC, merged